/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d605c94f4f9e97325c0f662
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { TaskService } from '../../services/task.service';
// Import Models
import { Task } from '../../domain/my-first-project_db/task';

// START - USED SERVICES
/**
* TaskService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* TaskService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Task
 * @class TaskListComponent
 */
@Component({
    selector: 'app-task-list',
    templateUrl: './task-list.component.html',
    styleUrls: ['./task-list.component.css']
})
export class TaskListComponent implements OnInit {
    list: Task[];
    search: any = {};
    idSelected: string;
    constructor(
        private taskService: TaskService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.taskService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Task to remove
     *
     * @param {string} id Id of the Task to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Task
     */
    deleteItem() {
        this.taskService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
