/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d605c94f4f9e97325c0f662
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { TaskService } from '../../services/task.service';
import { UserService } from '../../services/user.service';
// Import Models
import { Task } from '../../domain/my-first-project_db/task';
import { User } from '../../domain/my-first-project_db/user';

// START - USED SERVICES
/**
* TaskService.create
*	@description CRUD ACTION create
*	@param String name name of task
*	@param Number userid users ID
*
* UserService.findBytasks
*	@description CRUD ACTION findBytasks
*	@param Objectid key Id della risorsa tasks da cercare
*
* TaskService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* TaskService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Task
 */
@Component({
    selector: 'app-task-edit',
    templateUrl: 'task-edit.component.html',
    styleUrls: ['task-edit.component.css']
})
export class TaskEditComponent implements OnInit {
    item: Task;
    listTasks: Task[];
    externalUser: User[];
    model: Task;
    formValid: Boolean;

    constructor(
    private taskService: TaskService,
    private userService: UserService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Task();
        this.externalUser = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.taskService.get(id).subscribe(item => this.item = item);
                this.userService.findByTasks(id).subscribe(list => this.externalUser = list);
            }
            // Get relations
        });
    }


    /**
     * Save Task
     *
     * @param {boolean} formValid Form validity check
     * @param Task item Task to save
     */
    save(formValid: boolean, item: Task): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.taskService.update(item).subscribe(data => this.goBack());
            } else {
                this.taskService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



